# Generated by Django 5.1.5 on 2025-04-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_users_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(
                max_length=32, unique=True, verbose_name="telegram id"
            ),
        ),
    ]
