# Generated by Django 5.1.5 on 2025-04-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="message_id",
            field=models.CharField(
                max_length=32, unique=True, verbose_name="message id"
            ),
        ),
    ]
