# Generated by Django 5.1.5 on 2025-05-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_alter_question_message_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="chat_session_id",
            field=models.CharField(
                blank=True, max_length=52, null=True, verbose_name="chat-session-id"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="success",
            field=models.BooleanField(blank=True, null=True, verbose_name="success"),
        ),
    ]
