# Generated by Django 5.1.5 on 2025-04-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="telegram_id",
            field=models.CharField(
                max_length=32, unique=True, verbose_name="telegram_id"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="username"
            ),
        ),
    ]
