# Generated by Django 5.1.5 on 2025-05-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_telegram_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("RU", "Russian"), ("EN", "English"), ("HE", "Hebrew")],
                default="EN",
                max_length=2,
                verbose_name="language",
            ),
        ),
    ]
