# Generated by Django 5.1.5 on 2025-05-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="access",
            field=models.BooleanField(default=False, verbose_name="access"),
        ),
    ]
