name: Linters

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Set up cache
      uses: actions/cache@v4
      with:
        path: .venv
        key: ${{ runner.os }}-poetry-dev-${{ hashFiles('poetry.lock') }}
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install linters
      run: |
        poetry install --only linters --no-root
    - name: Web | Black
      run: |
        poetry run black web --check --diff --color
    - name: Web | Flake8
      run: |
        poetry run flake8 web --statistics --count --show-source
    - name: Telegram bot | Black
      run: |
        poetry run black telegram_bot --check --diff --color
    - name: Telegram bot | Flake8
      run: |
        poetry run flake8 telegram_bot --statistics --count --show-source
